import Head from 'next/head';
import { generate } from './api/generate';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Superteam Earnings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-16">
        <p className="mb-12 text-5xl font-bold text-white">Earnings v3? 🚀🚧</p>
        <Link href="/projects" className="block text-2xl text-white underline">
          projects
        </Link>
        <Link
          href="/rainmakers"
          className="block text-2xl text-white underline"
        >
          rainmakers
        </Link>
        <Link href="/sponsors" className="block text-2xl text-white underline">
          sponsors
        </Link>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  let data = await generate();

  return {
    props: {
      ...data,
    }, // will be passed to the page component as props
  };
}
